Information:
  Title: Discreetshare Blog
  Description: Welcome to our blog that allows our users to see our advances
  Link: discreetshare.com
  Theme: Default

Connections:
  GitHub: 
  YouTube:
  Twitter: 
